### ISSUE TITLE
Support return value sequences

### ISSUE THREAD

**Issue by codehearts** [codehearts/shpy#3]
I'm really liking shpy so far, especially its support for subshells! I have a function which calls a stub multiple times, and I'm not able to test cases where the stub returns a different value on subsequent calls.

My thought would be supporting a `createSpy -r 0 -r 1 -r 2 spyName` syntax, and always return the last value after finishing the sequence.

**Comment by mkropat** [comment]
Hey, thanks for the interest! I like the syntax you suggest, and I've found that exact functionality very useful when testing with other (non-shell) test frameworks.

However, none of the projects I work on these days rely on shpy, so I'm not personally interested in maintaining this project.

Since very few people use this project, it should be really easy to fork at this point. Do you want to fork the library and be the new maintainer? Alternatively, I'd be happy to give you commit access to this repo if you prefer.

If you do fork, I recommend not using Github's fork functionality but doing it manually (create your repo, then push shpy to your repo) to avoid this text:

![image](https://user-images.githubusercontent.com/979677/38631629-438ee0b6-3d88-11e8-8d12-bf8b8634773a.png)

(IMO the "forked from" just makes it more confusing for users to figure out what the active fork is.)

Once you've created the fork I can update the README to point to your repo.

**Comment by codehearts** [comment]
I wouldn't mind taking it over, would you rather transfer the repo to me or have me fork it?

Are you using something else for stubs in shell tests at this point?

**Comment by mkropat** [comment]
Oh cool. I didn't even know about repo transfers. Transfer initiated.

Nope, I'm not using any library. The only shell code I currently maintain that uses spies for the tests is [jumpapp](https://github.com/mkropat/jumpapp/blob/master/t/test_jumpapp), but it only uses them in a really basic way so I opted to not use any library there.

**Comment by mkropat** [comment]
Thank you for taking over the project! I forget to set my expectations around taking over the project, which are: I have no expectations. Go forth and do what you think is best 😄
